[tasks.release]
description = """
$ mise run build 1.9.2
$ mise run build 1.9.2-beta
"""
run = [
	"pnpm run build", # check tsc
	"pnpm vitest run",
	"pnpm version {{arg(name='VERSION')}}",
	"git push --tags",
	"git push"
]
